### ISSUE TITLE
Bridge topics

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#100]
We don't really do this currently because of the semantics between "should we use the matrix topic" or "should we use the IRC topic".  I propose:
 - Add a new config section:

   ```yaml
   # Controls how topics should be set between Matrix/IRC
   topics:
      # Use the topics set in these rooms instead of any IRC one
      useRooms: ["!foo:bar", "!baz:quuz"]
      # Use the topics set in these channels instead of any IRC one
      useChannels: ["#chan", "#chan2"]
      # If neither room nor channel match the lists above, use the topic from irc|matrix
      default: "irc"
   ```

Edge cases:
 - If a room matches both `useChannels` and `useRooms` then the topic will not be bridged at all (current behaviour).
 - If syncing M->I topics and the virtual IRC client fails to set the topic (not ops), then [1]
 - If syncing I->M topics and the virtual Matrix user fails to set the topic (no power), **and** the bridge bot cannot grant the user power, then [1]
 - [1] = Do one of the following:
    * [PM] : Send a **PM** from the bridge bot to the originator of the topic to say `ERROR: Failed to bridge topic.`
    * [SRC] : Send a message into the **source room** as the bridge bot (who may not be joined) to say `ERROR: Failed to bridge topic`.
    * [DST] : Send a message into the **destination room** as the virtual user to say `ERROR: I can't set the topic`.
    * [NOP] : Silently fail.

My feeling is probably [PM] but this is horrible because often the topic is set by an individual who may not be in the room anymore or may not really contribute/follow the room much at all. In this case, PMs will be sent to them to say "waaah waaaah I can't bridge! SADPANDA!" which feels really horrible.

Rationale:
 - Not part of explicit `mappings` because you may want a specific dynamically bridged channel to use a different topic.
 - Whilst the bug is mainly to do with bridging IRC topics to Matrix, also including the inverse for symmetry.
