### ISSUE TITLE
Dynamically joining rooms does not work

### ISSUE THREAD

**Issue by IngwiePhoenix** [matrix-org/matrix-appservice-irc#1007]
Hey!

Before I go any further, I should point out that I am visually impaired and can not always read everything - even if I try, there is a chance I overlooked something.

So, with this said... I am stuck. I am trying to configure this bridge to access the GNOME IRC channel (irc.gnome.org #a11y). I went through the how-to, did not configure any static mappings (so that I can just un-join those rooms and leave the IRC server there for when I need it the next time).

However, I can not seem to invite the bridge (`sender_name: irc_bot` and thus inviting as `@irc_bot:<domain>`) nor dynamically join channels (edited the templates - which is reflected in the registration file).

In fact, this is the registration file with some stuff redacted for obvious reasons:

```yaml
# id, as_token and hs_token stripped
namespaces:
  users:
    - exclusive: true
      regex: '@irc_irc\.gnome\.org_.*:ingwie\.io'
  aliases:
    - exclusive: true
      regex: '#irc_irc\.gnome\.org_.*:ingwie\.io'
  rooms: []
url: 'http://localhost:8008'
sender_localpart: irc_bot
rate_limited: false
protocols:
  - irc
```

When starting the app, I do see that it successfuly connects to the IRC server and receives ping messages. However, doing a `/join #irc_irc.gnome.org_#a11y:ingwie.io` (tested with both `#a11y` and `a11y`)  doesn't get me anywhere - nothing in the logs of the bridge at all. But what I do see is that this registration file is indeed loaded.

I maybe should mention that I reverse-proxy `matrix.ingwie.io` to `localhost:8008` to get my Let's Encrypt certs working properly, hence I connect with HTTP internally, but have it SSL'd from the outside. This works with the Discord, Telegram and WhatsApp bridge just fine, so this shouldn't be an issue.

Did I oversee something htere? What options do I have to verify that everything is working as expected?

Kind regards,
Ingwie
