### ISSUE TITLE
Appservice bot does not accept join requests for direct chats

### ISSUE THREAD

**Issue by junaru** [matrix-org/matrix-appservice-irc#1009]
### What works:
I'm trying to bridge single "#channel" (mode: +RSZnrstz ) from irc.data.lt (Unreal3.2.10.6) to "!DZmWmHtOiSJtlslJoD:redacted.com" on self hosted synapse 1.11.0 with matrix-appservice-irc 0.16.0.

The bot successfully connects to IRC network,  identifies to NickServ, joins the IRC channel, populates "!DZmWmHtOiSJtlslJoD:redacted.com" with IRC users and messages from IRC users show up in matrix room.
### What doesn't:
However the bot ignores direct chat invites and never joins them, so no one can interact with it via !help:
![failed_join](https://user-images.githubusercontent.com/59161/76700243-5b4fd780-66be-11ea-8b4c-1b223846a69d.png)

### What i tried:
 * Changing bot name (localpart)
 * Changing matrix room to another
 * Deleting all matrix-appserver-irc database files 
 * Rewriting homeserver.yaml and config.yaml based on most recent examples.

I doubt this is a bug but more of a miss-configuration on my end. Nothing catches my eye in both synapse and matrix-appservice-irc logs but i'm not even sure what to look for. Any hints would be much appreciated.

### Configs:
/etc/matrix-appservice-irc/config.yaml:
````
homeserver:
  url: "https://redacted.com"
  domain: "redacted.com"
  enablePresence: true
  bindHostname: "127.0.0.1"
ircService:
  servers:
    irc.data.lt:
      name: "Aitvaras"
      port: 6668
      ssl: true
      sslselfsign: false
      sasl: false
      allowExpiredCerts: false
      sendConnectionMessages: true
      quitDebounce:
        enabled: false
        quitsPerSecond: 5
        delayMinMs: 3600000 # 1h
        delayMaxMs: 7200000 # 2h
      modePowerMap:
        o: 50
        v: 1
      botConfig:
        enabled: true
        nick: "neo"
        password: "*********************"
        joinChannelsIfNoUsers: true
      privateMessages:
        enabled: true
        federate: true
      dynamicChannels:
        enabled: false
        createAlias: true
        published: true
        joinRule: public
        groupId: +myircnetwork:localhost
        federate: true
        aliasTemplate: "#irc_$CHANNEL"
      membershipLists:
        enabled: true
        floodDelayMs: 10000
        global:
          ircToMatrix:
            initial: true
            incremental: true
          matrixToIrc:
            initial: true
            incremental: true
        rooms:
          - room: "!DZmWmHtOiSJtlslJoD:redacted.com"
            matrixToIrc:
              initial: true
              incremental: true
        channels:
          - channel: "#channel"
           channel ircToMatrix:
              initial: true
              incremental: true
      mappings:
        "#channel":
          roomIds: ["!DZmWmHtOiSJtlslJoD:redacted.com"]
      matrixClients:
        userTemplate: "@irc_$NICK"
        displayName: "$NICK (IRC)"
        joinAttempts: -1
      ircClients:
        nickTemplate: "$DISPLAY[m]"
        allowNickChanges: true
        maxClients: 30
        ipv6:
          only: false
        idleTimeout: 10800
        reconnectIntervalMs: 5000
        concurrentReconnectLimit: 50
        lineLimit: 3
  bridgeInfoState:
    enabled: true
    initial: true
  ident:
    enabled: false
    port: 1113
    address: "::"
  logging:
    level: "debug"
    logfile: "debug.log"
    errfile: "errors.log"
    toConsole: true
    maxFiles: 5
  metrics:
    enabled: true
    remoteUserAgeBuckets:
      - "1h"
      - "1d"
      - "1w"
  debugApi:
    enabled: false
    port: 11100
  provisioning:
    enabled: false
    requestTimeoutSeconds: 300
    ruleFile: "./provisioning.rules.yaml"
    enableReload: true
  passwordEncryptionKeyPath: "/var/matrix-appservice-irc/passkey.pem"
  matrixHandler:
    eventCacheSize: 4096
  ircHandler:
    leaveConcurrency: 10
    mapIrcMentionsToMatrix: "on" # This can be "on", "off", "force-off".
advanced:
  maxHttpSockets: 1000
  maxTxnSize: 10000000
sentry:
  enabled: false
  dsn: "https://<key>@sentry.io/<project>"
database:
  engine: "nedb"
  connectionString: "nedb://data"

````
/etc/matrix-appservice-irc/appservice-registration-irc-2020.yaml:
````
id: ************
hs_token: ************
as_token: ******************
namespaces:
  users:
    - exclusive: true
      regex: '@irc_.*:redacted\.com'
  aliases: []
  rooms:
    - exclusive: false
      regex: '!DZmWmHtOiSJtlslJoD:redacted.com'
url: '127.0.0.1:9999'
sender_localpart: neo2
rate_limited: false
protocols:
  - irc
````
/etc/synapse/homeserver.yaml:
````
server_name: "redacted.com"
pid_file: /etc/synapse/homeserver.pid
federation_ip_range_blacklist:
  - '127.0.0.0/8'
  - '10.0.0.0/8'
  - '172.16.0.0/12'
  - '192.168.0.0/16'
  - '100.64.0.0/10'
  - '169.254.0.0/16'
  - '::1/128'
  - 'fe80::/64'
  - 'fc00::/7'
listeners:
  - port: 8448
    type: http
    tls: true
    bind_addresses: ['0.0.0.0']
    resources:
      - names: [client, federation]
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false
retention:
tls_certificate_path: "/etc/synapse/redacted.com.pem"
tls_private_key_path: "/etc/synapse/redacted.com.key"
tls_dh_params_path: "/etc/synapse/redacted.com.tls.dh"
acme:
    enabled: false
    port: 80
    bind_addresses: ['::', '0.0.0.0']
    reprovision_threshold: 30
    domain: matrix.example.com
    account_key_file: /etc/synapse/acme_account.key
database:
  name: "sqlite3"
  args:
    database: "/mnt/data/synapse/homeserver.db"
log_config: "/etc/synapse/redacted.com.log.config"
media_store_path: "/mnt/data/synapse/"
max_upload_size: 24M
max_image_pixels: 32M
account_validity:
registration_shared_secret: "*********************************"
account_threepid_delegates:
metrics_flags:
report_stats: false
app_service_config_files:
   - "/etc/matrix-appservice-irc/appservice-registration-irc-2020.yaml"
macaroon_secret_key: "*************************************"
form_secret: "************************************"
signing_key_path: "/etc/synapse/redacted.com.signing.key"
old_signing_keys:
trusted_key_servers:
  - server_name: "matrix.org"
saml2_config:
  user_mapping_provider:
    config:
password_config:
email:
opentracing:
````
Theres nginx reverse proxy on https://redacted.com with:
````
        location /_matrix {  
            proxy_pass http://127.0.0.1:8008;
            access_log  off;
        }                           
````
synapse-mnt-data.service:
````
[Unit]
Description=Synapse Matrix homeserver
After=network-online.target
Requires=network-online.target

[Service]
Type=simple
User=synapse
Group=synapse
SyslogIdentifier=synapse
Environment=LANG=en_US.UTF-8
WorkingDirectory=/mnt/data/synapse
ExecStart=/usr/bin/python3 -m synapse.app.homeserver --config-path=/etc/synapse/homeserver.yaml
ExecStop=/usr/bin/synctl stop /etc/synapse/homeserver.yaml
EnvironmentFile=-/etc/default/synapse

[Install]
WantedBy=multi-user.target
````
matrix-appservice-irc.service:
````
[Unit]
Description=Matrix IRC Bridge
Documentation=https://github.com/matrix-org/matrix-appservice-irc
Requires=synapse-mnt-data.service
After=network.target synapse-mnt-data.service

[Service]
User=matrix-appservice-irc
Group=matrix-appservice-irc
WorkingDirectory=/var/matrix-appservice-irc
ExecStart=/usr/bin/node /usr/lib/node_modules/matrix-appservice-irc/app.js -c /etc/matrix-appservice-irc/config.yaml -f /etc/matrix-appservice-irc/appservice-registration-irc-2020.yaml -p 9999

# The following loads the freebindfree library, which is required for individual IPv6 addresses.
# This needs to be installed separately, see the main configuration.
# Environment=LD_PRELOAD=/opt/freebindfree/libfreebindfree.so

# Allow more open file descriptors, useful for a large bridge
# LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
````

**Comment by junaru** [comment]
From description #1007 might be reporting the same issue.

**Comment by IngwiePhoenix** [comment]
> From description #1007 might be reporting the same issue.

Almost. I did not previously set up a direct matrix<->irc link within the config, but was rather just telling the bridge that I would like it to recognize rooms from those servers, so that I could `/join` them at will. I personally am not a big fan of static configuration of channels - but that is just my preference. So I wanted to use the dynamic creation of rooms for that...but, it doesn't seem to trigger when I request to join a room that technically fits an alias.

**Comment by junaru** [comment]
@IngwiePhoenix  Just curious, can you start a direct chat with @irc_bot:ingwie.io (i asume this is your bot account name) and type "!help" in it?
If the bot responds successfully it would rule out the possibility of these issues being related.

**Comment by IngwiePhoenix** [comment]
@junaru 
![image](https://user-images.githubusercontent.com/2893716/76731190-23e43800-675d-11ea-8d3f-5758802be9cc.png)

I think this explains everything :p 

The bot also does not appear online either - I have tried several times of changing or updating my config and what have you. But it just never wants to respond.

**Comment by junaru** [comment]
@ingwiePhoenix Yep, i tried the docker approach from Dockerfile.README and got exact same results - bot joins irc etc but woun't respond so it dosen't look like its a problem with the runtime environment.

P.S. i think the docker command in Dockerfile.README should be:
`docker run -p 9995:9995 -v $PWD/dockerdata:/data`

**Comment by Half-Shot** [comment]
Hey @junaru, sorry to hear you are having issues. I suspect my advice in #1007 applies to you too.

**Comment by junaru** [comment]
Hey @Half-Shot, i've set my logging to look as follows (changed root level to DEBUG, everything else default):
````
version: 1
 formatters:
    precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
 filters:
    context:
        (): synapse.logging.context.LoggingContextFilter
        request: ""
 handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: precise
        filename: /etc/synapse/homeserver.log
        maxBytes: 104857600
        backupCount: 10
        filters: [context]
        encoding: utf8
    console:
        class: logging.StreamHandler
        formatter: precise
        filters: [context]
 loggers:
    synapse.storage.SQL:
        # beware: increasing this to DEBUG will make synapse log sensitive
        # information such as access tokens.
        level: INFO
 root:
    level: DEBUG
    handlers: [file, console]
disable_existing_loggers: false
````

The [homeserver.log.bz2](https://junaru.com/homeserver.log.bz2) covers starting synapse and matrix-appservice-irc, requesting direct chat with the bot (neo2), bot never joining, typing "!help" three times, waiting ~15 seconds and shutting down synapse.

There are some suspicious retry messages in the log file:
````
2020-03-18 11:56:19,381 - synapse.appservice.scheduler - 205 - INFO - as_scheduler-0 - Starting recoverer for AS ID <matrix-appservice-irc id>
````
Can you take a look at the full log? Thanks.
