### ISSUE TITLE
membershipLists inital for specific rooms is not working [M -> I]

### ISSUE THREAD

**Issue by e1mo** [matrix-org/matrix-appservice-irc#1063]
We want to mirror all users that are in one specific matrix to IRC so that virtual IRC Users are created for everyone who is able to read messages. Our configuration looks like this:

```yaml
      membershipLists:
        enabled: true
        floodDelayMs: 10000
        global:
          ircToMatrix:
            initial: false
            incremental: false
          matrixToIrc:
            initial: false
            incremental: false
        rooms:
          - room: "!yMromrRUzExxxxxxxx:our.matrix.tld"
            matrixToIrc:
              initial: true
              incremental: true
```

### Expected behavior

We expect, upon restarting the appservice using the new configuration, to join all matrix users which are in the specified room (`!yMromrRUzExxxxxxxx:our.matrix.tld`) to be joined in to the IRC counterpart. We also expect users which join and or leave to be joined in to the IRC room.

### Actual behavior

The `incremental` option works (joins/and leaves are being synchronized) while the room-specific `inital` option doesn't seem to have any effect. If we turn set `initial: true` globally it works as expected.

This may be related to #371 

- Version: latest docker container (docker pull matrixdotorg/matrix-appservice-irc:latest)
- IRC Network: Hackint
