### ISSUE TITLE
Channel aliasTemplate restrictions are too tight

### ISSUE THREAD

**Issue by frebib** [matrix-org/matrix-appservice-irc#1395]
**Describe the bug**

https://github.com/matrix-org/matrix-appservice-irc/pull/1339/commits/7e5e16108041795ae40ab5517bb93900b0eeb277#diff-fa9ffcf960283f4c104fdc294f7fac2e833e4f180bb6d47cde21e050e705ac07R320 broke by aliasTemplates, which worked just fine before. Can the trailing `$` be removed? I don't see any reason why the `$CHANNEL` must be the last thing in the alias.

A snippet of my config
```
    irc.libera.chat:
      <<: *freenode
      name: libera
      networkId: libera
      dynamicChannels:
        <<: *dynamicChannels
        aliasTemplate: "#irc_$CHANNEL_libera"
      matrixClients:
        <<: *matrixClients
        userTemplate: "@irc_$NICK_libera"

    irc.oftc.net:
      <<: *freenode
      name: oftc
      networkId: oftc
      #sasl: true
      dynamicChannels:
        <<: *dynamicChannels
        aliasTemplate: "#irc_$CHANNEL_oftc"
      matrixClients:
        <<: *matrixClients
        userTemplate: "@irc_$NICK_oftc"
```

Fails with the following error
```
Error: Failed to validate file
    at ConfigValidator.validate (/app/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:75:23)
    at Cli.loadConfig (/app/node_modules/matrix-appservice-bridge/lib/components/cli.js:207:26)
    at Cli.assignConfigFile (/app/node_modules/matrix-appservice-bridge/lib/components/cli.js:187:29)
    at Cli.run (/app/node_modules/matrix-appservice-bridge/lib/components/cli.js:179:14)
    at Object.<anonymous> (/app/app.js:79:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  _validationErrors: [
    {
      field: 'data.ircService.servers[keys2.0].dynamicChannels.aliasTemplate',
      message: 'pattern mismatch',
      value: '#irc_$CHANNEL_freenode',
      type: 'string',
      schemaPath: [
        'properties',
        'ircService',
        'properties',
        'servers',
        'additionalProperties',
        'properties',
        'dynamicChannels',
        'properties',
        'aliasTemplate'
      ]
    },
    {
      field: 'data.ircService.servers[keys2.1].dynamicChannels.aliasTemplate',
      message: 'pattern mismatch',
      value: '#irc_$CHANNEL_libera',
      type: 'string',
      schemaPath: [
        'properties',
        'ircService',
        'properties',
        'servers',
        'additionalProperties',
        'properties',
        'dynamicChannels',
        'properties',
        'aliasTemplate'
      ]
    },
    {
      field: 'data.ircService.servers[keys2.2].dynamicChannels.aliasTemplate',
      message: 'pattern mismatch',
      value: '#irc_$CHANNEL_oftc',
      type: 'string',
      schemaPath: [
        'properties',
        'ircService',
        'properties',
        'servers',
        'additionalProperties',
        'properties',
        'dynamicChannels',
        'properties',
        'aliasTemplate'
      ]
    }
  ]
}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
