### ISSUE TITLE
Settings are mixed up between IRC servers

### ISSUE THREAD

**Issue by HackerFoo** [matrix-org/matrix-appservice-irc#26]
Settings are mixed up between IRC servers.
For example:

```
ircService:
  servers:
    irc.server1.net:
      port: 9999
    irc.server2.net:
      port: 6667
```

matrix-appservice-irc will sometimes try to connect to irc.server1.net on port 6667, or irc.server2.net on port 9999. It seems to be order dependent; I can get it to work by reordering the servers.
