### ISSUE TITLE
Generated regexes in appservice config accept any HS

### ISSUE THREAD

**Issue by roblabla** [matrix-org/matrix-appservice-irc#28]
The namespaces generated by the generate command are too liberal, in that they will also forward messages from remote rooms that have their own aliases.

For example, my AS is configured with a `#freenode_` alias. I would expect it to only bridge channels that have a LOCAL alias e.g. `#freenode_#matrix:cmc.im`. However, the generated config : 

```
namespaces:
  users:
    - exclusive: true
      regex: '@freenode_.*:.*'
  aliases:
    - exclusive: true
      regex: '#freenode_.*:.*'
```

means that my HS is sending events from #freenode_#matrixhq:matrix.org to my AS.
