### ISSUE TITLE
Bridge bot doesn't reconnect after a lost connection

### ISSUE THREAD

**Issue by silkeh** [matrix-org/matrix-appservice-irc#862]
On the IRCnet bridge the bridge bot (for some reason) tends to get disconnected after some time. 
When that happens, the bridge bot doesn't reconnect, leaving all Bot-related functionality broken.

Bot config:

```yaml
      botConfig:
        enabled: false
        nick: SNTMatrixBot
        joinChannelsIfNoUsers: false
```

My sneaking suspicion is that this is caused by  [this check](https://github.com/matrix-org/matrix-appservice-irc/blob/3c68b6f82692ef4bdfa16b00a9de13089d8a063d/lib/irc/ClientPool.js#L402), but I cannot confirm because we have the bridge set to log level `warn`.
