### ISSUE TITLE
ERROR:CLI Failed to run bridge without additional info

### ISSUE THREAD

**Issue by bobpaul** [matrix-org/matrix-appservice-irc#988]
When I try to run the bridge, I get this:
```
$ node --version
v12.16.0
$ node app.js -c /etc/synapse/matrix-appservice-irc/config-freenode.yaml -f /etc/synapse/matrix-appservice-irc/registration-freenode.yaml 
2020-02-16 19:37:02 ERROR:CLI Failed to run bridge
```
The debug and error logs only contain the same, generic error. It's already giving debug output, so I don't think I can make it anymore verbose...

**Comment by Half-Shot** [comment]
Hmm, this is the latest version of the bridge?

**Comment by bobpaul** [comment]
Yeah, from git. `75ca02`. I'll try the `0.15.2` tag.

**Comment by pierreN** [comment]
Same issue here, switching to 0.15.2 or 0.15.0 doesn't change anything. Applying the following diff:

```
diff --git a/app.js b/app.js
index 0abb586f..81e428df 100644
--- a/app.js
+++ b/app.js
@@ -50,7 +50,7 @@ new Cli({
             port = null;
         }
         const bridge = main.runBridge(port, config, reg).catch(function(err) {
-            log.error("Failed to run bridge.", err);
+            log.error("Failed to run bridge.", err, "...");
             process.exit(1);
         });

```

allows to get the error for me I think :

```
2020-02-21 05:52:36 INFO:IrcBridge Using PgDataStore for Datastore
2020-02-21 05:52:36 INFO:CryptoStore Private key loaded from passkey.pem - IRC password encryption enabled.
2020-02-21 05:52:36 INFO:PgDatastore Starting postgres database engine
(node:12477) DeprecationWarning: prom-client - Passing a non-object to metrics constructor is deprecated
(node:12477) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2020-02-21 05:52:36 INFO:PgDatastore Database schema is at version v10
2020-02-21 05:52:36 ERROR:CLI Failed to run bridge. error: column "origin" does not exist
    at Connection.parseE (/home/synapse/matrix-appservice-irc/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/home/synapse/matrix-appservice-irc/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/home/synapse/matrix-appservice-irc/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:321:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  name: 'error',
  length: 106,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '25',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3293',
  routine: 'errorMissingColumn'
} ...
```

I'm using postgres.  I guess it's because some postgres table is not created ? But could'nt find anywhere doc to create the postgres tables. Did I miss something ?

**Comment by john-stone** [comment]
Same issue on node v13.9.0. Tried `75ca02` `0.15.2` and `0.15.0`. Same error every time with no further log output. At least none that I could find.

**Comment by Half-Shot** [comment]
Can you both try running `39fb1d21053813ef2533c9e53784de537d00fa8c` and see what the output is?

**Comment by john-stone** [comment]
```
ircbridge@localhost:~/matrix-appservice-irc$ node app.js -c config.yaml -f irc_registration.yaml -p 9999
2020-02-21 10:17:39 ERROR:CLI Failed to run bridge.
2020-02-21 10:17:39 ERROR:CLI
```

**Comment by Half-Shot** [comment]
yay :|

**Comment by Half-Shot** [comment]
ugh, fatfingered

**Comment by Half-Shot** [comment]
Okay, would both of you mind sharing your config files, replacing any sensitive bits?

**Comment by john-stone** [comment]
Initially, I tried to modify the sample config but I ended up just using the minimal settings outlined in the [how-to](https://github.com/matrix-org/matrix-appservice-irc/blob/master/HOWTO.md).

```
# This section contains information about the HS
homeserver:
  # This url will be used by the AS to perform Client-Server API calls.
  url: "http://localhost:8008"
  # This value will be used when forming user IDs under certain
  # circumstances. This is typically the domain part of the 'url' field
  # above.
  domain: "domain.xyz"

ircService:
  servers:
    # This is the IRC server url to connect to.
    irc.server.com:
      mappings:
        "#channel":
          roomIds: ["!eejVWgLRxPpxlNiS:domain.xyz"]
```
For the url I've tried the domain, the domain with port and localhost with port, same result each time.

**Comment by Half-Shot** [comment]
I think you've been bitten by #899, and we should really fix this. I would definitely read the sample config and see if you can get it to look like that.

**Comment by john-stone** [comment]
Same error using the following.
https://gist.github.com/john-stone/60d16f81c123186adb351fe327048b4e

**Comment by Half-Shot** [comment]
What happens if you define the database section (just make it a nedb database)

**Comment by john-stone** [comment]
That squared it. Thanks for the help and sorry for the trouble.

**Comment by Half-Shot** [comment]
No worries, we need better logging for that failure mode. Does this help you @bobpaul ?

**Comment by bobpaul** [comment]
I didn't read any guides and just tried to set it up by filling in the sample config. My database section looked like this:

```
# Use an external database to store bridge state.
database:
  # database engine (must be 'postgres' or 'nedb'). Default: nedb
  engine: "nedb"
   # Either a PostgreSQL connection string, or a path to the NeDB storage directory.
   # For postgres, it must start with postgres://
   # For NeDB, it must start with nedb://. The path is relative to the project directory.
  connectionString: "nedb://nedb.db"
```
